# image path, level, resistances, demon race
demon_info = {
    'Lham Dearg': ['img/lham_dearg', 1, 'weak: ice, resist: gun and phys', 'Jaki'],
    'Centaur': ['img/centaur', 1, 'weak: elec, resist: gun, null: ice', 'Yoma'],
    'Fuxi': ['img/fuxi', 1, 'weak: gun, resist: force', 'Raptor'],
    'Tangata Manu': ['img/tangata_manu', 2, 'weak: gun and elec, null: force', 'Flight'],
    'Napaea': ['img/napaea', 2, 'weak: ice, resist: force', 'Fairy'],
    'Mokoi': ['img/mokoi', 2, 'weak: force, null: elec', 'Night'],
    'Slime': ['img/slime', 2, 'weak: gun, fire, ice, elec, force, light', 'Foul'],
    'Hamsa': ['img/hamsa', 3, 'weak: gun, resist: elec', 'Avian'],
    'Angel': ['img/angel', 3, 'weak: darkness, null: light', 'Divine'],
    'Heqet': ['img/heqet', 3, 'weak: fire, resist: elec', 'Holy'],
    'Gryphon': ['img/gryphon', 3, 'weak:gun, null: force', 'Beast'],
    'Myrmecolion': ['img/myrmecolion', 3, 'weak: elec', 'Vermin'],
    'Onmoraki': ['img/onmoraki', 3, 'weak: gun and ice', 'food'],
    'Dwarf': ['img/dwarf', 4, 'weak: force, resist: fire', 'Jirae'],
    'Dybbuk': ['img/dybbuk', 4, 'weak: ice and light, resist: darkness', 'Spirit'],
    'Samurai Zombie M': ['img/samurai_zombie_m', 4, 'weak: fire and light, null: darkness', 'Undead'],
    'Melcholm': ['img/melcholm', 5, 'weak: ice and force, resist: darkness, repel: fire', 'Fallen'],
    'Grudge Horde': ['img/grudge_horde', 5, 'weak: fire and light, null: darkness', 'Horde'],
    'Samurai Zombie F': ['img/samurai_zombie_f', 5, 'weak: fire and light, null: darkness', 'Undead'],
    'Vodyanik': ['img/vodyanik', 6, 'weak: force, null: elec', 'Yoma'],
    'Chagrin': ['img/chagrin', 6, 'weak: elec, repel: force', 'Wilder'],
    'Pele': ['img/pele', 6, 'weak": ice, null: fire', 'Lady'],
    'Strigoii': ['img/strigoii', 6, 'weak: fire and light, resist: elec, force, and darkness', 'Ghost'],
    'Pixie': ['img/pixie', 7, 'null: force', 'Fairy'],
    'Bilwis': ['img/bilwis', 7, 'weak: light, null: darkness', 'Brute'],
    'Fomorian': ['img/fomorian', 7, 'weak: fire, null: ice', 'Night'],
    'Apsaras': ['img/apsaras', 8, 'weak: fire, absorb: ice', 'Nymph'],
    'Stonka': ['img/stonka', 8, 'weak: gun and elec', 'Beast'],
    'Knocker': ['img/knocker', 8, ' weak: elec, null: force', 'Jirae'],
    'Wicker Man': ['img/wicker_man', 8, 'weak: fire, elec, and light, null: darkness', 'Spirit'],
    'Erthys': ['img/erthys', 8, 'weak: force, null: light and darkness, absorb: elec', 'Element'],
    'Harpy': ['img/harpy', 9, 'weak: gun and elec, repel: force', 'Flight'],
    'Camazotz': ['img/camazotz,', 9, 'weak: gun', 'Raptor'],
    'Zhu Tun She': ['img/zhu_tun_she', 9, 'weak: light, null: gun and ice', 'Drake'],
    'Jack the Ripper': ['img/jack_the_ripper', 9, 'weak: fire', 'Foul'],
    'Katakirauwa': ['img/katakirauwa', 9, 'weak: fire, ice, elec, force, and light, resist: phys, null: darkness', 'Food'],
    'Gremlin': ['img/gremlin', 10, 'weak: fire and force, resist: elec', 'Jaki'],
    'Fortuna': ['img/fortuna', 11, 'absorb: force', 'Megami'],
    'Spriggan': ['img/spriggan', 11, 'weak: light and darkness, resist: phys and elec', 'Fairy'],
    'Naga': ['img/naga', 11, 'weak: fire, resist: elec, null: ice', 'Snake'],
    'Mothman': ['img/mothman', 11, 'weak: force, null: darkness', 'Vermin'],
    'Leanan Sidhe': ['img/leanan_sidhe', 11, 'weak: force', 'Femme'],
    'Agathion': ['img/agathion', 12, 'weak: gun and ice, absorb: fire'],
    'Jueyuan': ['img/jueyuan', 12, 'weak: force, null: fire', 'Wilder'],
    'Bifrons': ['img/bifrons', 12, 'weak: weak: force, null: fire', 'Fallen'],
    'Preta': ['img/preta', 12, 'weak: fire, force, and light, null: ice and darkness', 'Ghost'],
    'Aeros': ['img/aeros', 12, 'weak: elec, null: light and darkness, absorb: elec', 'Element'],
    'Gaea Man': ['img/gaea_man', 12, 'repel: gun and darkness', 'Human'],
    'Tam Lin': ['img/tam_lin', 13, 'weak: ice, null: light', 'Genma'],
    'Kaso': ['img/kaso', 13, 'weak: ice, null: fire', 'Beast'],
    'Makara': ['img/makara', 13, 'absorb: ice', 'Dragon'],
    'Oni': ['img/oni', 13, 'No weaknesses or resistances', 'Brute'],
    'Poltergeist': ['img/poltergeist', 13, 'weak: foce and light', 'Spirit'],
    'Wildfire Horde': ['img/wildfire_horde', 13, 'resist: elec and darkness, absorb: fire', 'Horde'],
    'Shan Xiao': ['img/shan_xiao', 14, 'resist: ice', 'Wood'],
    'Shiisaa': ['img/shiisaa', 14, 'weak: darkness, resist: elec and force, null: fire and light', 'Avatar'],
    'Hua Po': ['img/hua_po', 14, 'weak: elec, null: fire', 'Jirae'],
    'Sandman': ['img/sandman', 14, 'weak: elec, absorb: force', 'Night'],
    'Suparna': ['img/suparna', 15, 'weak: darkness, resist: light, null: elec', 'Avian'],
    'Jack Frost': ['img/jack_frost', 15, 'weak: fire, absorb: ice', 'Fairy'],
    'Morax': ['img/morax', 15, 'weak: ice, null: darkness, repel: fire', 'Tyrant'],
    'Toubyou': ['img/toubyou', 15, 'No weaknesses or resistances', 'Drake'],
    'Mamedanuki': ['img/mamedanuki', 15, 'resist: fire and ice', 'Food'],
    'Gu Huo Niao': ['img/gu_huo_niao', 16, 'weak: ice, resist: force, repel: gun', 'Flight'],
    'Hooligan': ['img/hooligan', 16, 'weak: ice and force, resist: gun, null: elec', 'Foul'],
    'Aquans': ['img/aquans', 16, 'weak: fire, null: light and darkness, absorb: ice', 'Element'],
    'Spirit Horde': ['img/spirit_horde', 16, 'weak: resist: phys, null: gun and darkness, repel: ice', 'Horde'],
    'Ashura Man': ['img/ashura_man', 16, 'weak: darkness, null: light', 'Human'],
    'Moh Shuvuu': ['img/moh_shuvuu', 17, 'weak: gun and fire, resist: force', 'Raptor'],
    'Ippon-Datara': ['img/ippon_datara', 17, 'weak: light, null: fire', 'Jaki'],
    'Dzelarhons': ['img/dzelarhons', 17, 'weak: ice, null: darkness, repel: fire', 'Lady'],
    'Strix': ['img/strix', 17, 'weak: gun and elec, resist: darkness, repel: ice', 'Femme'],
    'Zombie Cop': ['img/zombie_cop', 17, 'weak: fire and light, null: darkness', 'Undead'],
    'Saki Mitama': ['img/saki_mitama', 17, 'null: elec, light, and darkness', 'Mitama'],
    'Hathor': ['img/hathor', 18, 'weak: elec, resist: force and light', 'Megami'],
    'Archangel': ['img/archangel', 18, 'weak: darkness, null: light', 'Divine'],
    'Koppa Tengu': ['img/koppa_tengu', 18, 'weak: elec, null: force', 'Yoma'],
    'Apis': ['img/apis', 18, 'weak: darkness', 'Holy'],
    'Ictinike': ['img/ictinike', 18, 'weak: force, null: light, absorb: fire', 'Genma'],
    'Nozuchi': ['img/nozuchi', 18, 'weak: fire, resist: phys, ice, and elec', 'Snake'],
    'Raijuu': ['img/raijuu', 18, 'weak: force, null: gun, absorb: elec', 'Wilder'],
    'Obariyon': ['img/obariyon', 18, 'weak: ice, null: elec', 'Ghost'],
    'Daphne': ['img/daphne', 19, 'weak: fire', 'Tree'],
    'Pyro Jack': ['img/pyro_jack', 19, 'weak: ice, repel: fire', 'Fairy'],
    'Kabuso': ['img/kabuso', 19, 'weak: elec, resist: fire and ice', 'Beast'],
    'Sudama': ['img/sudama', 19, 'weak: fire, absorb: elec', 'Jirae'],
    'Halphas': ['img/halphas', 19, 'weak: gun and force, resist: darkness', 'Fallen'],
    'Azumi': ['img/azumi', 19, 'weak: elec, null: ice', 'Brute'],
    'Quicksilver': ['img/quicksilver', 19, 'weak: force and light, null: gun, repel: elec'],
    'Kikimora': ['img/kikimora', 20, 'weak: force, null: ice', 'Night'],
    'Flaemis': ['img/flaemis', 20, 'weak: ice, null: light and darkness, absorb: fire', 'Element'],
    'Demonstrators': ['img/demonstrators', 20, 'null: darkness, repel: gun and elec', 'Horde'],
    'Kusi Mitama': ['img/kusi_mitama', 20, 'null: force, light, and darkness', 'Mitama'],
    'Mithras': ['img/mithras', 21, 'weak: ice, resist: fire, null: light', 'Tyrant'],
    'Chupacabra': ['img/chupacabra', 21, 'weak: elec, resist: light and darkness'],
    'Take-Minakata': ['img/take_minakata', 21, 'weak: fire', 'resist: light and darkness, absorb: elec'],
    'Mandrake': ['img/mandrake', 22, 'weak: fire', 'Wood'],
    'Ubu': ['img/ubu', 22, 'weak: light', 'null: gun', 'Vermin'],
    'David': ['img/david', 22, 'weak: elec, resist: fire, ice, and light, null: darkness'],
    'Ame no Uzume': ['img/ame_no_uzume', 22, 'weak: gun and elec, null: light', 'Amatsu'],
    'Caladrius': ['img/caladrius', 23, 'weak: gun and darkness, null: light', 'Flight'],
    'Itsumade': ['img/itsumade', 23, 'weak: ice, null: force', 'Raptor'],
    'Patrimpas': ['img/patrimpas', 23, 'weak: light and darkness, resist: ice, repel: force', 'Dragon'],
    'Shikome': ['img/shikome', 23, 'weak: light, null: darkness', 'Femme'],
    'Bai Suzhen': ['img/bai_suzhen', 23, 'weak: fire, null: ice', 'Drake'],
    'Night Stalker': ['img/night_stalker', 23, 'weak: light', 'Foul'],
    'Karasa Tengu': ['img/karasa_tengu', 24, 'weak: ice and elec, null: light, repel: fire', 'Yoma'],
    "Kamapua'a": ["img/kamapuaa", 24, 'weak: ice and force, resist: fire and elec', 'Avatar'],
    'Nata Taishi': ['img/nata_taishi', 24, 'resist: phys, gun, light, and darkness', 'Genma'],
    'Goblin': ['img/goblin', 24, 'weak: elec', 'Fairy'],
    'Kwancha': ['img/kwancha', 24, 'weak: force', 'Jirae'],
    'Mou-Ryo': ['img/mou_ryo', 24, 'weak: light, null: darkness', 'Ghost'],
    'Ogun': ['img/ogun', 24, 'null: fire', 'Zealot'],
    'Gnome': ['img/gnome', 24, 'weak: force, null: light and darkness, repel: elec', 'Element'],
    'Parvati': ['img/parvati', 25, 'weak: fire, null: light and darkness, absorb: ice', 'Megami'],
    'Phoenix': ['img/phoenix', 25, 'weak: ice, resist: light, absorb: fire', 'Avian'],
    'Senri': ['img/senri', 25, 'weak: elec and darkness, absorb: force', 'Nymph'],
    'Inugami': ['img/inugmi', 25, 'weak: force and light, null: darkness, repel: fire', 'Beast'],
    'Wendigo': ['img/wendigo', 25, 'weak: fire, repel: ice', 'Jaki'],
    'Momunofu': ['img/momunofu', 25, 'weak: force, resist: phys', 'Brute'],
    'Macabre': ['img/macabre', 25, 'weak: gun and light, null: darkness'],
    'Tattooed Man': ['img/tattooed_man', 25, 'weak: darkness, null: light', 'Foul'],
    'Hoodlum Horde': ['img/hoodlum_horde', 25, 'resist: phys and gun, null: light', 'Horde'],
    'Jirae Horde': ['img/jirae_horde', 25, 'weak: fire, resist: phys, absorb: elec', 'Horde'],
    'Principality': ['img/principality', 26, 'weak: gun and darkness, null: light', 'Divine'],
    'Baphomet': ['img/baphomet', 26, 'weak: light, null: darkness', 'Vile'],
    'Pabilsag': ['img/pabilsag', 26, 'weak: elec, repel: gun', 'Holy'],
    'Vouivre': ['img/vouivre', 26, 'weak: fire, resist: elec, ice: null', 'Snake'],
    'Nue': ['img/nue', 26, 'weak: gun and force, absorb: elec', 'Wilder'],
    'Orias': ['img/orias', 26, 'weak: ice, resist: darkness, absorb: fire', 'Fallen'],
    'Sedna': ['img/sedna', 27, 'weak: fire and light, null: darkness, absorb: ice', 'Lady'],
    'Horkos': ['img/horkos', 27, 'weak: fire, resit: phys and darkness', 'Tyrant'],
    'Kanbari': ['img/kanbari', 27, 'weak: phys and darkness, null: gun and light', 'Enigma'],
    'Ashura Woman': ['img/ashura_woman', 27, 'weak: darkness, null: light', 'Human'],
    'Narcissus': ['img/narcissus', 28, 'weak: fire, absorb: force', 'Tree'],
    'High Pixie': ['img/high_pixie', 28, 'resist: force', 'Fairy'],
    'Incubus': ['img/incubus', 28, 'weak: elec, resist: darkness, absorb: force', 'Night'],
    'Kuda': ['img/kuda', 28, 'weak: gun and force, repel: ice', 'Food'],
    'Sylph': ['img/sylph', 28, 'weak: elec, null: light and darkness, repel: force', 'Element'],
    'Tuofei': ['img/tuofei', 29, 'weak: gun, resist: repel', 'Flight'],
    'Skogsra': ['img/skogsra', 29, 'weak: fire, resist: force, null: gun', 'Wood'],
    'Baldur': ['img/baldur', 29, 'weak: gun, resist: phys, null: elec', 'Genma'],
    'Okiku-Mushi': ['img/okiku_mushi', 29, 'weak: ice, force, and light, null: gun', 'Vermin'],
    'Yuki Jyorou': ['img/yuki_jyorou', 29, 'weak: fire, absorb: ice', 'Femme'],
    'Dis': ['img/dis', 30, 'weak: gun, absorb: ice', 'Yoma'],
    'Thoth': ['img/thoth', 30, 'weak: gun and darkness, null: fire and ice', 'Deity'],
    'Tsuchigumo': ['img/tsuchigumo', 30, 'weak: ice, repel: elec', 'Jirae'],
    'Basilisk': ['img/basilisk', 30, 'weak: force, null: darkness', 'Drake'],
    'Imperial Guard': ['img/imperial_guard', 30, 'resist: phys and gun, null: light and darkness, absorb: force', 'Horde'],
    'Zombie': ['img/zombie', 30, 'weak: fire and light, null: darkness', 'Undead'],
    'Nigi Mitama': ['img/nigi_mitama', 30, 'null: light and darkness, absorb: ice', 'Mitama'],
    'Zhen': ['img/zhen', 31, 'resist: darkness', 'Raptor'],
    'Hairy Jack': ['img/hairy_jack', 31, 'weak: light, resist: darkness', 'Beast'],
    'Black Frost': ['img/black_frost', 31, 'resist: phys, null: darkness, repel: fire, absorb: ice', 'Jaki'],
    'Ares': ['img/ares', 31, 'weak: darkness, null: light', 'Fury'],
    'Yamawaro': ['img/yamawaro', 31, 'weak: light and darkness, resist: phys and ice', 'brute'],
    'Inferno': ['img/inferno', 31, 'weak: ice and light, absorb: fire', 'Spirit'],
    'Babylonian Horde': ['img/babylonian_horde', 31, 'resist: phys, null: gun, light, and darkness', 'Horde'],
    'Makami': ['img/makami', 32, 'null: light', 'Avatar'],
    'Setanta': ['img/setnta', 32, 'repel: force', 'Fairy'],
    'Dantalian': ['img/dantalian', 32, 'weak: elec, resist:fire, ice and darkness, null: force', 'Fallen'],
    'Samyaza': ['img/samyaza', 32, 'weak: force, null: darkness', 'Tyrant'],
    'Churel': ['img/churel', 32, 'weak: light, null: darkness', 'Ghost'],
    'Undine': ['img/undine', 32, 'fire, null: light and darkness, repel: ice', 'Element'],
    'Brigid': ['img/brigid', 33, 'weak: ice, absorb: fire', 'Megami'],
    'Vidofnir': ['img/vidofnir', 33, 'weak: gun, null: light', 'Avain'],
    'Power': ['img/power', 33, 'weak: force and darkness, null: light', 'Divine'],
    'Qing Niugai': ['img/qing_niugai', 33, 'resist: phys', 'Holy'],
    'Minotaur': ['img/minotaur', 33, 'weak: ice, null: fire and darkness', 'Beast'],
    'Yurlungur': ['img/yurlungur', 33, 'weak: fire, resist: elec, absorb: ice', 'Snake'],
    'Peallaidh': ['img/peallaidh', 33, 'weak: fire, null: ice', 'Wilder'],
    'Gucumatz': ['img/gucumatz', 33, 'weak: fire and darkness, resist: force, absorb: ice', 'Dragon'],
    'Lilim': ['img/lilim', 33, 'weak: ice, null: force', 'Night'],
    'Frost Ace': ['img/frost_ace', 34, 'repel: fire and ice', 'Genma'],
    'Okuninushi': ['img/okuninushi', 34, 'weak: ice, resist: light and darkness', 'Kunitsu'],
    'Gaea Woman': ['img/gaea_woman', 34, 'repel: phys and darkness', 'Human'],
    'Lailah': ['img/lailah', 35, 'weak: elec, null: light', 'Herald'],
    'Mayahuel': ['img/mayahuel', 35, 'weak: fire, null: gun', 'Tree'],
    'Inti': ['img/inti', 35, 'weak: elec, null: fire and ice', 'Deity'],
    'Medusa': ['img/medusa', 35, 'weak: force, resist: gun, absorb: elec', 'Femme'],
    'Corpses': ['img/corpses', 35, 'weak: fire, elec, and light, null: gun, ice, and darkness', 'Undead'],
    'Fairy Horde': ['img/fairy_horde', 35, 'weak: gun, resist: phys, fire, ice, and elec, absorb: force', 'Horde'],
    'Ara Mitama': ['img/ara_mitama', 35, 'null: light and darkness, repel: fire', 'Mitama'],
    'Kikuri-Hime': ['img/kikuri_hime', 36, 'weak: elec and darkness, null: force and light', 'Nymph'],
    'Kelpie': ['img/kelpie', 36, 'weak: force, resist: ice', 'fairy'],
    'Hariti': ['img/hariti', 36, 'resist: darkness', 'lady'],
    'Yoshitsune': ['img/yoshitsune', 36, 'resit: gun, null: light and darkness', 'Famed'],
    'Salamander': ['img/salamander', 36, 'weak: ice, null: light and darkness, repel: fire', 'Element'],
    'Mishaguji': ['img/mishaguji', 37, 'weak: ice, null: darkness, repel: elec', 'Vile'],
    'Nekomata': ['img/nekomata', 37, 'weak: ice and elec, repel: fire, absorb: force', 'Beast'],
    'Titan': ['img/titan', 37, 'resist: phys', 'Jirae'],
    'Tonatiuh': ['img/tonatiuh', 37, 'weak: ice, resist: fire and darkness', 'Fury'],
    'Zouchouten': ['img/zouchouten', 37, 'weak: ice, resist: darkness, null: fire and light', 'Kishin'],
    'Yomotsu-Ikusa': ['img/yomotsu_ikusa', 37, 'weak: light, resist: darkness', 'Brute'],
    'Clotho': ['img/clotho', 37, 'weak: force, null: fire, light, and darkness', 'Femme'],
    'King Frost': ['img/king_frost', 37, 'weak: fire, null: light and darkness, absorb: ice', 'Tyrant'],
    'Shiwanna': ['img/shiwanna', 38, 'weak: fire, resist: phys, absorb: ice', 'Yoma'],
    'Rakshasa': ['img/rakshasa', 38, 'weak: force and light, resist: phys', 'Jaki'],
    'Ose': ['img/ose']
}
